'use strict'

const ActionTypes = {
  LOAD_DRIVERS:          'LOAD_DRIVERS',
  ADD_DRIVER:            'ADD_DRIVER',
  UPDATE_DRIVER:         'UPDATE_DRIVER',
  DELETE_DRIVER:         'DELETE_DRIVER',
  UPDATE_DRIVER_DETAILS: 'UPDATE_DRIVER_DETAILS',
  SHOW_DRIVER_DETAILS:   'SHOW_DRIVER_DETAILS',
  HIDE_DRIVER_DETAILS:   'HIDE_DRIVER_DETAILS',
  SHOW_POPUP:            'SHOW_POPUP',
  HIDE_POPUP:            'HIDE_POPUP'
}

export default ActionTypes
