'use strict'

const ActionTypes = {
  LOAD_DRIVERS:              'LOAD_DRIVERS',
  TOGGLE_GENERAL_ACTIVITY:   'TOGGLE_GENERAL_ACTIVITY',
  TOGGLE_DAILY_ACTIVITY:     'TOGGLE_DAILY_ACTIVITY',
  TOGGLE_NOCTURNAL_ACTIVITY: 'TOGGLE_NOCTURNAL_ACTIVITY',
  SHOW_DRIVER_DETAILS:       'SHOW_DRIVER_DETAILS',
  HIDE_DRIVER_DETAILS:       'HIDE_DRIVER_DETAILS',
  SAVE_DRIVER_DETAILS:       'SAVE_DRIVER_DETAILS'
}

export default ActionTypes
