'use strict'

const ActionTypes = {
  LOAD_DRIVERS:              'LOAD_DRIVERS',
  TOGGLE_GENERAL_ACTIVITY:   'TOGGLE_GENERAL_ACTIVITY',
  TOGGLE_DAILY_ACTIVITY:     'TOGGLE_DAILY_ACTIVITY',
  TOGGLE_NOCTURNAL_ACTIVITY: 'TOGGLE_NOCTURNAL_ACTIVITY'
}

export default ActionTypes
